name: 'Auto Assign'
on:
  pull_request_target:
    branches:
      - master
  push:
    branches:
      - master
   

jobs:
  ready-for-review:
    name: PR Ready For Review
    if: github.event.action == 'ready_for_review' || (github.event.action == 'opened' && github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    steps:
      - name: add reviewers & assign author
        # https://github.com/kentaro-m/auto-assign-action
        uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: ${{ secrets.MYGITHUB_TOKEN }}
